"""Generate complete verified dictionaries for German, Spanish, Italian, and Russian."""
import os
import sys

sys.path.insert(0, "/home/word-sys/word-sys-pdf-editor")
from word_sys_pdf_editor.i18n import _STRINGS

en = _STRINGS["en"]

# German translation
de = {
    "app_subtitle": "Einfacher, schneller und quelloffener PDF-Editor",
    "btn_open": "Datei öffnen…",
    "btn_new": "Neues PDF",
    "btn_guide": "Schnellstartanleitung",
    "btn_cancel": "Abbrechen",
    "btn_confirm": "Bestätigen",
    "btn_copy": "Kopieren",
    "btn_copy_text": "Text kopieren",
    "btn_paste": "Einfügen",
    "btn_paste_new": "Als neuen Text einfügen",
    "btn_dont_save": "Nicht speichern",
    "recent_header": "<b>PDF-Dateien auf dem System</b>",
    "tip_prefix": "Tipp:",
    "tips": [
        "Tipp: Doppelklicken Sie auf einen Textblock, um ihn zu bearbeiten.",
        "Tipp: Strg + Mausrad zum Vergrößern und Verkleinern.",
        "Tipp: Wählen Sie ein Objekt aus und drücken Sie Entf, um es zu löschen.",
        "Tipp: Verwenden Sie das Verschieben-Werkzeug, um Text und Bilder zu positionieren.",
        "Tipp: Ziehen Sie eine PDF-Datei in das Fenster, um sie zu öffnen.",
        "Tipp: Verwenden Sie die Farbschaltfläche, um die Textfarbe zu ändern.",
        "Tipp: Verwenden Sie die Druckschaltfläche, um Ihr PDF zu drucken.",
        "Tipp: Verwenden Sie 'Speichern unter', um eine Kopie mit neuem Namen zu speichern.",
    ],
    "zoom_out_tip": "Verkleinern (Strg+Mausrad nach unten)",
    "zoom_in_tip": "Vergrößern (Strg+Mausrad nach oben)",
    "prev_page_tip": "Vorherige Seite",
    "next_page_tip": "Nächste Seite",
    "add_page_tip": "Neue Seite hinzufügen",
    "font_tip": "Schriftart",
    "font_size_tip": "Schriftgröße",
    "bold_tip": "Fett",
    "italic_tip": "Kursiv",
    "underline_tip": "Unterstrichen",
    "color_tip": "Textfarbe",
    "shape_fill_tip": "Formfüllfarbe",
    "shape_transparent_tip": "Transparent (keine Füllung) / Gefüllt",
    "shape_stroke_tip": "Formlinienfarbe",
    "shape_width_tip": "Formlinienbreite",
    "tool_select": "Auswählen (S)",
    "tool_select_tip": "Objekte auswählen & skalieren (S)",
    "tool_add_text": "Text (T)",
    "tool_add_text_tip": "Neuen Textblock hinzufügen (T)",
    "tool_add_image": "Bild (I)",
    "tool_add_image_tip": "Bild hinzufügen (I)",
    "tool_drag": "Verschieben (M)",
    "tool_drag_tip": "Objekte ziehen & verschieben (M)",
    "tool_ellipse": "Ellipse (C)",
    "tool_ellipse_tip": "Ellipsenform hinzufügen (C)",
    "tool_rectangle": "Rechteck (R)",
    "tool_rectangle_tip": "Rechteckform hinzufügen (R)",
    "tool_pen": "Stift (P)",
    "tool_pen_tip": "Freihand-Stiftlinien zeichnen (P)",
    "tool_highlighter": "Textmarker (H)",
    "tool_highlighter_tip": "Freihand-Textmarker (H)",
    "tool_checkmark": "Häkchen (V)",
    "tool_checkmark_tip": "Häkchen hinzufügen ✓ (V)",
    "tool_cross": "Kreuz (X)",
    "tool_cross_tip": "Kreuz hinzufügen ✗ (X)",
    "tooltip_symbols": "Sonderzeichen, Symbole & Emojis",
    "tab_symbols": "Symbole",
    "tab_emojis": "Emojis",
    "symbol_copied": "'{}' in die Zwischenablage kopiert",
    "stroke_color_tip": "Strich- / Stiftfarbe",
    "stroke_width_tip": "Strich- / Stiftbreite",
    "pages_label": "Seiten",
    "delete_page_tip": "Ausgewählte Seite löschen",
    "loading": "Lade {}…",
    "thumbnails_loading": "Lade Vorschaubilder…",
    "thumbnail_loaded": "Vorschaubild geladen {}/{}",
    "loaded": "Geladen: {}",
    "new_doc_loaded": "Neues Dokument geladen.",
    "saving": "Speichere {}…",
    "saved": "Gespeichert und neu geladen: {}",
    "save_failed": "Speichern fehlgeschlagen.",
    "doc_load_failed": "Dokument konnte nicht geladen werden.",
    "scan_fonts": "Systemschriftarten werden gesucht…",
    "unsaved_changes": "Es gibt ungespeicherte Änderungen. Möchten Sie vor dem Schließen/Öffnen speichern?",
    "unsaved_title": "Ungespeicherte Änderungen",
    "delete_page_confirm": "Möchten Sie diese Seite wirklich löschen?",
    "delete_confirm_title": "Seite löschen",
    "delete_text_confirm": "Ausgewählten Text löschen?\n'{}'",
    "delete_shape_confirm": "Möchten Sie die ausgewählte Form wirklich löschen?",
    "delete_image_confirm": "Möchten Sie das ausgewählte Bild wirklich löschen?",
    "delete_confirm": "Löschen",
    "do_not_ask_again": "Nicht mehr fragen",
    "menu_confirm_delete": "Vor dem Löschen von Objekten bestätigen",
    "menu_highlight": "Hervorheben",
    "menu_remove_highlight": "Hervorhebung entfernen",
    "menu_edit_text": "Text bearbeiten",
    "menu_delete_shape": "Form löschen",
    "menu_delete_image": "Bild löschen",
    "change_applied": "Änderung angewendet.",
    "reverted": "Rückgängig gemacht.",
    "object_added": "Objekt hinzugefügt.",
    "object_deleted": "Objekt gelöscht.",
    "delete_reverted": "Löschen rückgängig gemacht.",
    "page_info": "Seite {}",
    "page_info_count": "Seite {} / {}",
    "image_select_title": "Bilddatei auswählen",
    "image_filter_label": "Bilddateien",
    "image_add_error": "Beim Verarbeiten der Bilddatei ist ein Fehler aufgetreten:\n{}",
    "image_error_title": "Bildfehler",
    "image_extract_error": "Bilder von Seite {} konnten nicht extrahiert werden.\n{}",
    "object_moved": "Objekt verschoben.",
    "tool_changed": "Werkzeug gewechselt: {}",
    "home_button_tip": "Zurück zum Startbildschirm",
    "home_confirm": "Zurück zum Startbildschirm wechseln?\nUngespeicherte Änderungen gehen verloren, wenn Sie nicht zuerst speichern.",
    "home_confirm_title": "Zurück zum Startbildschirm",
    "export_success": "Erfolgreich exportiert.",
    "export_error": "Export fehlgeschlagen: {}",
    "lang_label": "Sprache",
    "lang_en": "English",
    "lang_tr": "Türkçe",
    "lang_fr": "Français",
    "lang_de": "Deutsch",
    "lang_es": "Español",
    "lang_it": "Italiano",
    "lang_ru": "Русский",
    "lang_restart_msg": "Die Anwendung wird neu gestartet, um die Sprachänderung anzuwenden.",
    "lang_restart_title": "Neustart erforderlich",
    "btn_new_doc": "Neu",
    "btn_open_doc": "Öffnen",
    "btn_save": "Speichern",
    "undo_tip": "Rückgängig (Strg+Z)",
    "redo_tip": "Wiederholen (Strg+Y)",
    "print_tip": "Drucken (Strg+P)",
    "menu_save_as": "Speichern unter…",
    "menu_export_as": "Exportieren als…",
    "menu_about": "Über",
    "menu_quick_guide": "Schnellstartanleitung",
    "menu_quit": "Beenden",
    "btn_done": "Fertig",
    "default_new_text": "Neuer Text",
    "untitled": "Ohne Titel",
    "status_open_or_drop": "Öffnen Sie eine Datei oder ziehen Sie eine hierher.",
    "guide_title": "Schnellstartanleitung",
    "guide_dialog_title": "Schnellstartanleitung & Handbuch",
    "guide_tab_tools": "Werkzeuge & Bearbeitung",
    "guide_tab_canvas": "Arbeitsfläche & Seiten",
    "guide_tab_shortcuts": "Tastenkürzel",
    "guide_grp_selection_text": "Auswahl & Typografie",
    "guide_tool_select_title": "Auswahl- & Verschiebewerkzeug",
    "guide_tool_select_desc": "Wählen Sie Text, Vektorformen oder Bilder aus. Ziehen Sie sie zum Neupositionieren oder nutzen Sie Pfeiltasten (Umschalt+Pfeil für 10pt). Doppelklicken Sie zum Bearbeiten.",
    "guide_tool_text_title": "Text hinzufügen & formatieren",
    "guide_tool_text_desc": "Klicken Sie an eine beliebige Stelle, um neue Textblöcke zu erstellen. Passen Sie Schriftart, Größe, Fett, Kursiv, Unterstreichung und Farbe an. Emojis über die Symbolschaltfläche.",
    "guide_tool_drag_title": "Schwenk- & Ziehwerkzeug",
    "guide_tool_drag_desc": "Klicken und ziehen Sie über die Seite, um die Ansicht flüssig zu verschieben, ohne Objekte aus Versehen zu markieren.",
    "guide_grp_drawing_shapes": "Freihandzeichnen & Vektorformen",
    "guide_tool_pen_title": "Freihand-Stiftwerkzeug",
    "guide_tool_pen_desc": "Schreiben Sie Notizen oder zeichnen Sie Skizzen. Linien werden automatisch in glatte Bézier-Kurven mit einstellbarer Breite und Farbe umgewandelt.",
    "guide_tool_highlighter_title": "Textmarker-Werkzeug",
    "guide_tool_highlighter_desc": "Heben Sie Textpassagen mit leuchtender, halbtransparenter Tinte hervor. Flache Linienenden halten Markierungen sauber innerhalb der Zeilen.",
    "guide_tool_shapes_title": "Geometrische Formen (Rechteck & Ellipse)",
    "guide_tool_shapes_desc": "Zeichnen Sie scharfe Vektorrechtecke und Ellipsen. Passen Sie Rahmenfarbe, Dicke und Füllfarbe an.",
    "guide_tool_markers_title": "Prüfmarkierungen (Häkchen & Kreuz)",
    "guide_tool_markers_desc": "Setzen Sie mit einem Klick Genehmigungshäkchen oder Ablehnungskreuze zum schnellen Ausfüllen und Korrigieren von Formularen.",
    "guide_tool_image_title": "Bilder & Logos einfügen",
    "guide_tool_image_desc": "Fügen Sie PNG-, JPEG- oder SVG-Grafiken ein. Transparente PNGs behalten ihren Alphakanal ohne dunkle Ränder bei.",
    "guide_grp_navigation": "Navigation & Verlauf",
    "guide_nav_focal_zoom_title": "Präzisions-Mauszeiger-Zoom",
    "guide_nav_focal_zoom_desc": "Halten Sie Strg gedrückt und scrollen Sie, um zentriert um den Mauszeiger zu zoomen. Strg++ zum Vergrößern, Strg+- zum Verkleinern, Strg+0 für 100 %.",
    "guide_nav_undo_title": "Mehrstufiges Rückgängigmachen & Wiederholen",
    "guide_nav_undo_desc": "Jede Aktion – Tippen, Formatieren, Bewegen, Zeichnen und Löschen – wird im Verlauf erfasst. Mit Strg+Z rückgängig machen, mit Strg+Y wiederholen.",
    "guide_grp_pages": "Seitenoperationen & Dokumentaufbau",
    "guide_pages_sidebar_title": "Seitenleisten-Sortierung per Drag-and-Drop",
    "guide_pages_sidebar_desc": "Sehen Sie Miniaturansichten aller Seiten in der linken Seitenleiste. Ziehen Sie Miniaturansichten per Drag-and-Drop, um Seiten neu anzuordnen.",
    "guide_pages_actions_title": "Seiten drehen, hinzufügen & löschen",
    "guide_pages_actions_desc": "Drehen Sie Seiten um 90° im oder gegen den Uhrzeigersinn, duplizieren Sie Seiten, fügen Sie leere Seiten ein oder löschen Sie Seiten.",
    "guide_pages_new_doc_title": "Anpassbare Dokumenterstellung",
    "guide_pages_new_doc_desc": "Erstellen Sie Dokumente mit 18 internationalen Vorlagen (A0–A6, B4–B5, US Letter/Legal, Folien, Quadrat) oder benutzerdefinierten Maßen mit Einheitenumrechnung.",
    "guide_grp_shortcuts_doc": "Datei & Dokument",
    "guide_sc_new": "Neues Dokument",
    "guide_sc_open": "PDF-Dokument öffnen",
    "guide_sc_save": "Dokument speichern",
    "guide_sc_save_as": "Speichern unter",
    "guide_sc_print": "Dokument drucken",
    "guide_sc_quit": "Anwendung beenden",
    "guide_grp_shortcuts_edit": "Bearbeiten & Arbeitsfläche",
    "guide_sc_undo": "Rückgängig",
    "guide_sc_redo": "Wiederholen",
    "guide_sc_zoom_in": "Vergrößern",
    "guide_sc_zoom_out": "Verkleinern",
    "guide_sc_zoom_reset": "Zoom zurücksetzen (100 %)",
    "guide_sc_zoom_scroll": "Mauszeiger-Zoom",
    "guide_sc_delete": "Ausgewähltes Objekt löschen",
    "guide_sc_deselect": "Auswahl aufheben / Abbrechen",
    "guide_sc_nudge": "Objekt fein verschieben (1 pt)",
    "guide_sc_nudge_fast": "Objekt weit verschieben (10 pt)",
    "guide_grp_shortcuts_tools": "Werkzeug-Tastenkürzel",
    "guide_sc_tool_select": "Auswahlwerkzeug",
    "guide_sc_tool_text": "Textwerkzeug",
    "guide_sc_tool_pen": "Stiftwerkzeug",
    "guide_sc_tool_highlighter": "Textmarker-Werkzeug",
    "guide_sc_tool_rect": "Rechteckform",
    "guide_sc_tool_ellipse": "Ellipsenform",
    "guide_sc_tool_check": "Häkchen-Markierung",
    "guide_sc_tool_cross": "Kreuz-Markierung",
    "guide_sc_tool_image": "Bild einfügen",
    "guide_sc_tool_drag": "Schwenkwerkzeug",
    "guide_item1": "<b>1. Auswahl- und Bearbeitungswerkzeug (S)</b>\nStandardwerkzeug. Klicken Sie auf Text oder Bilder, um sie auszuwählen. Doppelklicken Sie auf Text, um ihn zu bearbeiten.",
    "guide_item2": "<b>2. Text-Hinzufügen-Werkzeug (T)</b>\nKlicken Sie an die gewünschte Stelle. Geben Sie den Text ein und passen Sie Schriftart und Farbe an.",
    "guide_item3": "<b>3. Bild-Hinzufügen-Werkzeug (I)</b>\nKlicken Sie an die gewünschte Stelle und wählen Sie eine Bilddatei aus.",
    "guide_item4": "<b>4. Verschieben-Werkzeug (M)</b>\nKlicken und ziehen Sie Text oder Bilder, um ihre Position auf der Seite zu ändern.",
    "font_loading": "Schriftarten werden geladen…",
    "font_none_error": "<Keine Schriftart (Fehler)>",
    "font_none": "<Keine Schriftart>",
    "fonts_loaded_open": "Schriftarten geladen. Öffnen Sie eine Datei.",
    "font_warning_title": "Schriftart-Warnung",
    "font_warning_msg": "Keine passende Unicode-Schriftart gefunden. Sonderzeichen werden möglicherweise nicht korrekt dargestellt.",
    "shape_fill_dialog_title": "Formfüllfarbe auswählen",
    "shape_stroke_dialog_title": "Formlinienfarbe auswählen",
    "transparent_label": "Transparent",
    "about_comments": "word-sys's PDF Editor ist ein Open-Source-Werkzeug zur Bearbeitung von PDF-Inhalten unter Linux.",
    "about_website_label": "Projekt-GitHub-Seite",
    "about_tab_about": "Über",
    "about_tab_credits": "Danksagung",
    "about_tab_license": "Lizenz",
    "github_page": "Projekt-GitHub-Seite",
    "print_no_doc": "Bitte öffnen Sie ein PDF-Dokument zum Drucken.",
    "print_no_doc_title": "Kein Dokument geöffnet",
    "print_error_title": "Druckfehler",
    "print_failed": "Drucken fehlgeschlagen.",
    "print_cancelled": "Druckvorgang abgebrochen.",
    "print_error_occurred": "Beim Drucken ist ein Fehler aufgetreten.",
    "print_success": "Druckauftrag erfolgreich gesendet.",
    "print_in_progress": "Druckvorgang läuft…",
    "print_start_failed": "Drucken konnte nicht gestartet werden: {}",
    "err_pdf_save": "Fehler beim Speichern des PDFs: {}",
    "err_invalid_doc_page_extract": "Ungültiges Dokument oder Seitenindex für die Bildextraktion.",
    "warn_image_skipped": "Warnung: Ein Bild auf Seite {} (xref={}) wurde übersprungen: {}",
    "err_image_extract_page": "Fehler beim Extrahieren der Bilder von Seite {}: {}",
    "err_invalid_doc_page_add_image": "Ungültiges Dokument oder Seitennummer zum Hinzufügen des Bildes.",
    "err_image_file_not_found": "Bilddatei nicht gefunden: {}",
    "err_placing_image": "Fehler beim Platzieren des Bildes: {}",
    "err_invalid_doc_page_delete_image": "Ungültiges Dokument oder Seitennummer zum Löschen des Bildes.",
    "err_invalid_image_bbox": "Ungültiger Bildbegrenzungsrahmen.",
    "err_deleting_image": "Fehler beim Löschen des Bildes: {}",
    "err_invalid_doc_page_delete_shape": "Ungültiges Dokument oder Seitennummer zum Löschen der Form.",
    "err_invalid_shape_bbox": "Ungültiger Formbegrenzungsrahmen.",
    "err_deleting_shape": "Fehler beim Löschen der Form: {}",
    "err_creating_new_pdf": "Fehler beim Erstellen des neuen PDFs: {}",
    "success_blank_page_added": "Leere Seite am Ende hinzugefügt (Seite {})",
    "err_adding_page": "Fehler beim Hinzufügen der Seite: {}",
    "err_source_pdf_empty": "Quell-PDF ist leer.",
    "success_merged_pages": "{} Seiten erfolgreich zusammengeführt.",
    "err_merging_pdf": "Fehler beim Zusammenführen der PDFs: {}",
    "err_invalid_page_index": "Ungültiger Seitenindex.",
    "err_invalid_target_index": "Ungültiger Zielindex.",
    "success_page_already_there": "Seite befindet sich bereits an dieser Position.",
    "success_page_moved": "Seite {} an Position {} verschoben.",
    "err_moving_page": "Fehler beim Verschieben der Seite: {}",
    "err_no_doc_msg_alt": "Kein Dokument.",
    "err_cannot_delete_last_page": "Die letzte Seite kann nicht gelöscht werden. Das Dokument muss mindestens eine Seite enthalten.",
    "err_invalid_page_index_val": "Ungültiger Seitenindex: {}",
    "success_page_deleted": "Seite {} gelöscht.",
    "err_deleting_page": "Fehler beim Löschen der Seite: {}",
    "err_moving_shape": "Fehler beim Verschieben der Form: {}",
    "err_during_op": "Fehler während der Operation: {}",
    "dbg_embedded_font_found": "DEBUG: Verzeichnis der eingebetteten Schriftarten gefunden: {}",
    "err_embedded_font_not_found": "FEHLER: Verzeichnis der eingebetteten Schriftarten nicht gefunden: {}",
    "warn_scanning_dir": "Warnung: Fehler beim Scannen des Verzeichnisses {}: {}",
    "font_scan_completed": "Schriftarten-Scan abgeschlossen. {} Schriftfamilien gefunden.",
    "wait_font_scan": "Warte auf Abschluss des Schriftarten-Scans…",
    "err_font_scan_timeout": "FEHLER: Zeitüberschreitung beim Schriftarten-Scan.",
    "dbg_repaired_while_opening": "DEBUG: Diese PDF-Datei wurde beim Öffnen repariert.",
    "dbg_save_success": "DEBUG: Speichern erfolgreich. Lade Datei neu: {}",
    "btn_open_label": "_Öffnen",
    "btn_cancel_label": "_Abbrechen",
    "font_tip_original": "Schriftart (Original-PDF: {})",
    "dbg_discarding_unsaved": "Verwerfe ungespeicherte Änderungen.",
    "import_pdf_title": "PDF importieren",
    "import_pdf_confirm": "Möchten Sie '{}' in das aktuelle PDF einfügen oder öffnen?",
    "err_merge_title": "PDF-Zusammenführungsfehler",
    "open_pdf_title": "PDF-Datei öffnen",
    "save_as_title": "PDF speichern unter...",
    "export_as_title": "Exportieren als...",
    "status_exporting": "Exportiere als {}...",
    "err_unknown_export_format": "Unbekanntes Exportformat.",
    "status_exported": "Exportiert als {}: {}",
    "err_export_failed_msg": "Export fehlgeschlagen: {}",
    "err_export_unexpected": "Unerwarteter Fehler beim Exportieren: {}",
    "status_export_failed": "Export fehlgeschlagen.",
    "err_no_doc_msg": "Bitte öffnen oder erstellen Sie zuerst ein Dokument.",
    "err_no_doc_title": "Kein Dokument",
    "err_add_page_title": "Fehler beim Hinzufügen der Seite",
    "err_no_doc_open_msg": "Bitte öffnen Sie zuerst ein Dokument.",
    "err_cannot_delete_last_page_title": "Seite kann nicht gelöscht werden",
    "delete_page_warn_msg": "Seite {} wird gelöscht. Dieser Vorgang kann nicht rückgängig gemacht werden. Fortfahren?",
    "delete_page_warn_title": "Seite löschen",
    "err_delete_page_title": "Fehler beim Löschen der Seite",
    "err_move_page_title": "Fehler beim Verschieben der Seite",
    "err_fonts_scanning_msg": "Schriftarten werden noch gescannt. Bitte warten.",
    "err_fonts_scanning_title": "Schriftarten-Scan",
    "font_user_added": "{} (Benutzerdefiniert)",
    "err_delete_image_failed": "Bild konnte nicht gelöscht werden: {}",
    "delete_error_title": "Löschfehler",
    "dbg_applying_changes_before_tool": "Wende Änderungen vor Werkzeugwechsel an...",
    "dbg_tool_changed_to": "Werkzeug gewechselt zu: {}",
    "dbg_creating_drag_cmd": "DEBUG: Erstelle Befehl für Ziehvorgang.",
    "dbg_saving_pending_format_cmd": "DEBUG: Speichere ausstehende Formatänderung.",
    "status_new_doc_created": "Neues leeres Dokument erstellt. Bitte Änderungen speichern.",
    "err_adding_image_dialog": "Fehler beim Hinzufügen des Bildes: {}",
    "err_title": "Fehler",
    "mode_edit": "Bearbeiten",
    "mode_view": "Ansicht",
    "mode_toggle_tip": "Zwischen Ansichts- und Bearbeitungsmodus wechseln",
    "tools": "Werkzeuge",
    "highlight": "Hervorheben",
    "highlight_tip": "Ausgewählten Text hervorheben",
    "highlight_color_tip": "Hervorhebungsfarbe",
    "remove_highlight": "Hervorhebung entfernen",
    "remove_highlight_tip": "Hervorhebung vom Text entfernen",
    "save_error_title": "Speicherfehler",
    "text_extract_error": "Textstruktur von Seite {} konnte nicht extrahiert werden.\n{}",
    "highlight_failed": "Hervorhebung fehlgeschlagen: {}",
    "filter_pdf": "PDF-Dateien (*.pdf)",
    "filter_all": "Alle Dateien",
    "filter_word": "Word-Dokument (*.docx)",
    "filter_odt": "OpenDocument-Text (*.odt)",
    "filter_pptx": "PowerPoint-Präsentation (*.pptx)",
    "filter_odp": "OpenDocument-Präsentation (*.odp)",
    "filter_txt": "Textdatei (*.txt)",
    "new_doc_dialog_title": "Neues Dokument",
    "new_doc_create": "Erstellen",
    "new_doc_cancel": "Abbrechen",
    "new_doc_page_setup": "Seiteneinrichtung",
    "new_doc_template": "Vorlage",
    "new_doc_orientation": "Ausrichtung",
    "new_doc_portrait": "Hochformat",
    "new_doc_landscape": "Querformat",
    "new_doc_dimensions": "Abmessungen",
    "new_doc_unit": "Einheit",
    "new_doc_width": "Breite",
    "new_doc_height": "Höhe",
    "new_doc_document": "Dokument",
    "new_doc_num_pages": "Seitenanzahl",
    "new_doc_pages_desc": "Anfängliche leere Seiten",
    "new_doc_unit_mm": "Millimeter (mm)",
    "new_doc_unit_cm": "Zentimeter (cm)",
    "new_doc_unit_in": "Zoll (in)",
    "new_doc_unit_pt": "Punkte (pt)",
    "new_doc_unit_px": "Pixel (px @ 72 dpi)",
    "preset_a4": "A4 (210 × 297 mm)",
    "preset_a3": "A3 (297 × 420 mm)",
    "preset_a5": "A5 (148 × 210 mm)",
    "preset_a6": "A6 (105 × 148 mm)",
    "preset_a2": "A2 (420 × 594 mm)",
    "preset_a1": "A1 (594 × 841 mm)",
    "preset_a0": "A0 (841 × 1189 mm)",
    "preset_b4": "B4 (250 × 353 mm)",
    "preset_b5": "B5 (176 × 250 mm)",
    "preset_letter": "US Letter (8.5 × 11 in)",
    "preset_legal": "US Legal (8.5 × 14 in)",
    "preset_executive": "US Executive (7.25 × 10.5 in)",
    "preset_tabloid": "Tabloid / Ledger (11 × 17 in)",
    "preset_slide_16_9": "Folie 16:9 (1920 × 1080 pt)",
    "preset_slide_16_10": "Folie 16:10 (1920 × 1200 pt)",
    "preset_slide_4_3": "Folie 4:3 (1024 × 768 pt)",
    "preset_square": "Quadrat (1080 × 1080 pt)",
    "preset_custom": "Benutzerdefiniert...",
}
import unittest


class TestGermanLocales(unittest.TestCase):
    def test_german_dictionary_populated(self):
        self.assertGreater(len(de), 300)
        for k, v in de.items():
            self.assertTrue(v, f"Empty translation for {k}")


if __name__ == '__main__':
    unittest.main()
