"""Generate complete locales.py for French, German, Spanish, Italian, and Russian."""
import os
import sys
import json

base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, "/home/word-sys/word-sys-pdf-editor")

from word_sys_pdf_editor.i18n import _STRINGS

en = _STRINGS["en"]

# Mapping dictionary for French
fr = {
    "app_subtitle": "Éditeur PDF simple, rapide et open-source",
    "btn_open": "Ouvrir un fichier…",
    "btn_new": "Nouveau PDF",
    "btn_guide": "Guide de démarrage rapide",
    "btn_cancel": "Annuler",
    "btn_confirm": "Confirmer",
    "btn_copy": "Copier",
    "btn_copy_text": "Copier le texte",
    "btn_paste": "Coller",
    "btn_paste_new": "Coller comme nouveau texte",
    "btn_dont_save": "Ne pas enregistrer",
    "recent_header": "<b>Fichiers PDF sur le système</b>",
    "tip_prefix": "Astuce :",
    "tips": [
        "Astuce : Double-cliquez sur un bloc de texte pour le modifier.",
        "Astuce : Ctrl + Molette pour zoomer et dézoomer.",
        "Astuce : Sélectionnez un objet et appuyez sur Suppr pour le retirer.",
        "Astuce : Utilisez l'outil Déplacer pour repositionner textes et images.",
        "Astuce : Glissez-déposez un PDF sur la fenêtre pour l'ouvrir.",
        "Astuce : Utilisez le bouton Couleur pour changer la couleur du texte.",
        "Astuce : Utilisez le bouton Imprimer pour imprimer votre PDF.",
        "Astuce : Utilisez Enregistrer sous pour enregistrer une copie sous un autre nom.",
    ],
    "zoom_out_tip": "Dézoomer (Ctrl+Molette vers le bas)",
    "zoom_in_tip": "Zoomer (Ctrl+Molette vers le haut)",
    "prev_page_tip": "Page précédente",
    "next_page_tip": "Page suivante",
    "add_page_tip": "Ajouter une nouvelle page",
    "font_tip": "Police de caractères",
    "font_size_tip": "Taille de police",
    "bold_tip": "Gras",
    "italic_tip": "Italique",
    "underline_tip": "Souligné",
    "color_tip": "Couleur du texte",
    "shape_fill_tip": "Couleur de remplissage de la forme",
    "shape_transparent_tip": "Transparent (sans remplissage) / Rempli",
    "shape_stroke_tip": "Couleur du contour de la forme",
    "shape_width_tip": "Épaisseur du contour de la forme",
    "tool_select": "Sélectionner (S)",
    "tool_select_tip": "Sélectionner & Redimensionner des objets (S)",
    "tool_add_text": "Texte (T)",
    "tool_add_text_tip": "Ajouter un bloc de texte (T)",
    "tool_add_image": "Image (I)",
    "tool_add_image_tip": "Ajouter une image (I)",
    "tool_drag": "Déplacer (M)",
    "tool_drag_tip": "Glisser & Déplacer des objets (M)",
    "tool_ellipse": "Ellipse (C)",
    "tool_ellipse_tip": "Ajouter une forme ellipse (C)",
    "tool_rectangle": "Rectangle (R)",
    "tool_rectangle_tip": "Ajouter une forme rectangle (R)",
    "tool_pen": "Stylo (P)",
    "tool_pen_tip": "Dessin à main levée au stylo (P)",
    "tool_highlighter": "Surligneur (H)",
    "tool_highlighter_tip": "Surligneur à main levée (H)",
    "tool_checkmark": "Coche (V)",
    "tool_checkmark_tip": "Ajouter une coche ✓ (V)",
    "tool_cross": "Croix (X)",
    "tool_cross_tip": "Ajouter une croix ✗ (X)",
    "tooltip_symbols": "Caractères spéciaux, symboles & émojis",
    "tab_symbols": "Symboles",
    "tab_emojis": "Émojis",
    "symbol_copied": "'{}' copié dans le presse-papiers",
    "stroke_color_tip": "Couleur du trait / stylo",
    "stroke_width_tip": "Épaisseur du trait / stylo",
    "pages_label": "Pages",
    "delete_page_tip": "Supprimer la page sélectionnée",
    "loading": "Chargement de {}…",
    "thumbnails_loading": "Chargement des miniatures…",
    "thumbnail_loaded": "Miniature chargée {}/{}",
    "loaded": "Chargé : {}",
    "new_doc_loaded": "Nouveau document chargé.",
    "saving": "Enregistrement de {}…",
    "saved": "Enregistré et rechargé : {}",
    "save_failed": "Échec de l'enregistrement.",
    "doc_load_failed": "Impossible de charger le document.",
    "scan_fonts": "Analyse des polices système…",
    "unsaved_changes": "Des modifications ne sont pas enregistrées. Voulez-vous enregistrer avant de fermer/ouvrir ?",
    "unsaved_title": "Modifications non enregistrées",
    "delete_page_confirm": "Voulez-vous vraiment supprimer cette page ?",
    "delete_confirm_title": "Supprimer la page",
    "delete_text_confirm": "Supprimer le texte sélectionné ?\n'{}'",
    "delete_shape_confirm": "Voulez-vous vraiment supprimer la forme sélectionnée ?",
    "delete_image_confirm": "Voulez-vous vraiment supprimer l'image sélectionnée ?",
    "delete_confirm": "Supprimer",
    "do_not_ask_again": "Ne plus demander",
    "menu_confirm_delete": "Confirmer avant de supprimer des objets",
    "menu_highlight": "Surligner",
    "menu_remove_highlight": "Supprimer le surlignage",
    "menu_edit_text": "Modifier le texte",
    "menu_delete_shape": "Supprimer la forme",
    "menu_delete_image": "Supprimer l'image",
    "change_applied": "Modification appliquée.",
    "reverted": "Annulé.",
    "object_added": "Objet ajouté.",
    "object_deleted": "Objet supprimé.",
    "delete_reverted": "Suppression annulée.",
    "page_info": "Page {}",
    "page_info_count": "Page {} / {}",
    "image_select_title": "Sélectionner un fichier image",
    "image_filter_label": "Fichiers image",
    "image_add_error": "Une erreur est survenue lors du traitement du fichier image :\n{}",
    "image_error_title": "Erreur d'image",
    "image_extract_error": "Impossible d'extraire les images de la page {}.\n{}",
    "object_moved": "Objet déplacé.",
    "tool_changed": "Outil changé : {}",
    "home_button_tip": "Retour à l'écran d'accueil",
    "home_confirm": "Retourner à l'écran d'accueil ?\nLes modifications non enregistrées seront perdues.",
    "home_confirm_title": "Retour à l'accueil",
    "export_success": "Exportation réussie.",
    "export_error": "Échec de l'exportation : {}",
    "lang_label": "Langue",
    "lang_en": "English",
    "lang_tr": "Türkçe",
    "lang_fr": "Français",
    "lang_de": "Deutsch",
    "lang_es": "Español",
    "lang_it": "Italiano",
    "lang_ru": "Русский",
    "lang_restart_msg": "L'application va redémarrer pour appliquer le changement de langue.",
    "lang_restart_title": "Redémarrage requis",
    "btn_new_doc": "Nouveau",
    "btn_open_doc": "Ouvrir",
    "btn_save": "Enregistrer",
    "undo_tip": "Annuler (Ctrl+Z)",
    "redo_tip": "Rétablir (Ctrl+Y)",
    "print_tip": "Imprimer (Ctrl+P)",
    "menu_save_as": "Enregistrer sous…",
    "menu_export_as": "Exporter sous…",
    "menu_about": "À propos",
    "menu_quick_guide": "Guide de démarrage rapide",
    "menu_quit": "Quitter",
    "btn_done": "Terminé",
    "default_new_text": "Nouveau texte",
    "untitled": "Sans titre",
    "status_open_or_drop": "Ouvrez un fichier ou glissez-déposez-en un ici.",
    "guide_title": "Guide de démarrage rapide",
    "guide_dialog_title": "Guide de démarrage rapide & Manuel",
    "guide_tab_tools": "Outils & Édition",
    "guide_tab_canvas": "Canevas & Pages",
    "guide_tab_shortcuts": "Raccourcis",
    "guide_grp_selection_text": "Sélection & Typographie",
    "guide_tool_select_title": "Outil Sélectionner & Déplacer",
    "guide_tool_select_desc": "Sélectionnez du texte, des formes vectorielles ou des images. Glissez pour repositionner ou utilisez les touches fléchées. Double-cliquez sur un texte pour l'éditer. Glissez les 8 poignées pour redimensionner.",
    "guide_tool_text_title": "Ajouter & Formater du texte",
    "guide_tool_text_desc": "Cliquez n'importe où pour créer de nouveaux blocs de texte. Personnalisez la police, la taille, le gras, l'italique, le soulignement et la couleur. Utilisez le bouton Symboles pour les émojis.",
    "guide_tool_drag_title": "Outil Panoramique & Déplacement",
    "guide_tool_drag_desc": "Cliquez et glissez à travers la page pour faire défiler le canevas en douceur sans déplacer d'objets.",
    "guide_grp_drawing_shapes": "Dessin à main levée & Formes vectorielles",
    "guide_tool_pen_title": "Outil Stylo à main levée",
    "guide_tool_pen_desc": "Prenez des notes ou esquissez des dessins. Les tracés sont automatiquement convertis en courbes de Bézier lisses avec couleur et épaisseur réglables.",
    "guide_tool_highlighter_title": "Outil Surligneur",
    "guide_tool_highlighter_desc": "Surlignez des passages de texte avec une encre lumineuse semi-transparente délimitée proprement par des extrémités plates.",
    "guide_tool_shapes_title": "Formes géométriques (Rectangle & Ellipse)",
    "guide_tool_shapes_desc": "Dessinez des rectangles et des ellipses vectoriels nets. Personnalisez la couleur de bordure, l'épaisseur et la couleur de remplissage.",
    "guide_tool_markers_title": "Marqueurs de révision rapide (Coche & Croix)",
    "guide_tool_markers_desc": "Tamponnez d'un seul clic des coches d'approbation ou des croix de rejet pour réviser et annoter facilement des formulaires.",
    "guide_tool_image_title": "Insérer des images & logos",
    "guide_tool_image_desc": "Placez des graphiques PNG, JPEG ou SVG. Les PNG transparents préservent le canal alpha sans bordures sombres.",
    "guide_grp_navigation": "Navigation & Historique",
    "guide_nav_focal_zoom_title": "Zoom focal de précision",
    "guide_nav_focal_zoom_desc": "Maintenez Ctrl et utilisez la molette de la souris pour zoomer précisément autour du curseur. Ctrl++ pour zoomer, Ctrl+- pour dézoomer et Ctrl+0 pour réinitialiser à 100 %.",
    "guide_nav_undo_title": "Annulation & Rétablissement multi-niveaux",
    "guide_nav_undo_desc": "Chaque action — saisie, déplacement, tracés, dimensionnement et suppression — est suivie dans l'historique. Annulez avec Ctrl+Z et rétablissez avec Ctrl+Y.",
    "guide_grp_pages": "Opérations de page & Configuration du document",
    "guide_pages_sidebar_title": "Réorganisation par glisser-déposer dans la barre latérale",
    "guide_pages_sidebar_desc": "Affichez les miniatures de toutes les pages dans le volet gauche. Glissez-déposez n'importe quelle miniature pour réorganiser l'ordre des pages.",
    "guide_pages_actions_title": "Faire pivoter, ajouter & supprimer des pages",
    "guide_pages_actions_desc": "Faites pivoter des pages individuelles à 90° dans le sens horaire ou antihoraire, dupliquez des pages, insérez de nouvelles pages vierges ou supprimez des pages inutiles.",
    "guide_pages_new_doc_title": "Création de document personnalisable",
    "guide_pages_new_doc_desc": "Créez de nouveaux documents avec 18 préréglages internationaux (A0–A6, B4–B5, US Letter/Legal, Diapositives, Carré) ou dimensions personnalisées avec conversion en direct (mm, cm, in, pt, px).",
    "guide_grp_shortcuts_doc": "Fichier & Document",
    "guide_sc_new": "Nouveau document",
    "guide_sc_open": "Ouvrir un document PDF",
    "guide_sc_save": "Enregistrer le document",
    "guide_sc_save_as": "Enregistrer sous",
    "guide_sc_print": "Imprimer le document",
    "guide_sc_quit": "Quitter l'application",
    "guide_grp_shortcuts_edit": "Édition & Canevas",
    "guide_sc_undo": "Annuler",
    "guide_sc_redo": "Rétablir",
    "guide_sc_zoom_in": "Zoom avant",
    "guide_sc_zoom_out": "Zoom arrière",
    "guide_sc_zoom_reset": "Réinitialiser le zoom (100 %)",
    "guide_sc_zoom_scroll": "Zoom sous le pointeur",
    "guide_sc_delete": "Supprimer l'objet sélectionné",
    "guide_sc_deselect": "Désélectionner / Quitter l'éditeur",
    "guide_sc_nudge": "Déplacer légèrement l'objet (1 pt)",
    "guide_sc_nudge_fast": "Déplacer l'objet (10 pt)",
    "guide_grp_shortcuts_tools": "Raccourcis d'activation des outils",
    "guide_sc_tool_select": "Outil Sélectionner",
    "guide_sc_tool_text": "Outil Texte",
    "guide_sc_tool_pen": "Outil Stylo",
    "guide_sc_tool_highlighter": "Outil Surligneur",
    "guide_sc_tool_rect": "Forme Rectangle",
    "guide_sc_tool_ellipse": "Forme Ellipse",
    "guide_sc_tool_check": "Marqueur Coche",
    "guide_sc_tool_cross": "Marqueur Croix",
    "guide_sc_tool_image": "Ajouter une image",
    "guide_sc_tool_drag": "Outil Panoramique",
    "guide_item1": "<b>1. Outil Sélectionner et Modifier (S)</b>\nOutil par défaut. Cliquez sur du texte ou des images pour les sélectionner. Double-cliquez sur un texte pour ouvrir la fenêtre de modification.",
    "guide_item2": "<b>2. Outil Ajouter du texte (T)</b>\nCliquez là où vous souhaitez ajouter du texte. Saisissez votre texte et ajustez police, taille et couleur dans la barre d'outils.",
    "guide_item3": "<b>3. Outil Ajouter une image (I)</b>\nCliquez là où vous souhaitez placer une image, puis choisissez votre fichier image dans le sélecteur.",
    "guide_item4": "<b>4. Outil Déplacer (M)</b>\nAprès avoir sélectionné cet outil, cliquez et faites glisser n'importe quel texte ou image pour changer sa position.",
    "font_loading": "Chargement des polices…",
    "font_none_error": "<Aucune police (Erreur)>",
    "font_none": "<Aucune police>",
    "fonts_loaded_open": "Polices chargées. Ouvrez un fichier.",
    "font_warning_title": "Avertissement de police",
    "font_warning_msg": "Aucune police Unicode appropriée n'a été trouvée. La modification de textes avec des caractères spéciaux peut ne pas fonctionner correctement.",
    "shape_fill_dialog_title": "Sélectionner la couleur de remplissage",
    "shape_stroke_dialog_title": "Sélectionner la couleur du contour",
    "transparent_label": "Transparent",
    "about_comments": "word-sys's PDF Editor est un outil open-source pour éditer le contenu des fichiers PDF sous Linux.",
    "about_website_label": "Page GitHub du projet",
    "about_tab_about": "À propos",
    "about_tab_credits": "Crédits",
    "about_tab_license": "Licence",
    "github_page": "Page GitHub du projet",
    "print_no_doc": "Veuillez ouvrir un fichier PDF pour imprimer.",
    "print_no_doc_title": "Aucun document ouvert",
    "print_error_title": "Erreur d'impression",
    "print_failed": "L'impression a échoué.",
    "print_cancelled": "Opération d'impression annulée.",
    "print_error_occurred": "Une erreur est survenue lors de l'impression.",
    "print_success": "Impression envoyée avec succès.",
    "print_in_progress": "Impression en cours…",
    "print_start_failed": "Impossible de démarrer l'impression : {}",
    "err_pdf_save": "Erreur lors de l'enregistrement du PDF : {}",
    "err_invalid_doc_page_extract": "Document ou index de page invalide pour l'extraction d'images.",
    "warn_image_skipped": "Avertissement : Une image de la page {} (xref={}) a été ignorée : {}",
    "err_image_extract_page": "Erreur lors de l'extraction des images de la page {} : {}",
    "err_invalid_doc_page_add_image": "Document ou numéro de page invalide pour ajouter l'image.",
    "err_image_file_not_found": "Fichier image introuvable : {}",
    "err_placing_image": "Erreur lors du placement de l'image : {}",
    "err_invalid_doc_page_delete_image": "Document ou numéro de page invalide pour supprimer l'image.",
    "err_invalid_image_bbox": "Cadre de délimitation de l'image invalide.",
    "err_deleting_image": "Erreur lors de la suppression de l'image : {}",
    "err_invalid_doc_page_delete_shape": "Document ou numéro de page invalide pour supprimer la forme.",
    "err_invalid_shape_bbox": "Cadre de délimitation de la forme invalide.",
    "err_deleting_shape": "Erreur lors de la suppression de la forme : {}",
    "err_creating_new_pdf": "Erreur lors de la création du nouveau PDF : {}",
    "success_blank_page_added": "Page vierge ajoutée à la fin (Page {})",
    "err_adding_page": "Erreur lors de l'ajout de la page : {}",
    "err_source_pdf_empty": "Le PDF source est vide.",
    "success_merged_pages": "{} pages fusionnées avec succès.",
    "err_merging_pdf": "Erreur lors de la fusion du PDF : {}",
    "err_invalid_page_index": "Index de page invalide.",
    "err_invalid_target_index": "Index cible invalide.",
    "success_page_already_there": "La page est déjà à cette position.",
    "success_page_moved": "Page {} déplacée vers la position {}.",
    "err_moving_page": "Erreur lors du déplacement de la page : {}",
    "err_no_doc_msg_alt": "Aucun document.",
    "err_cannot_delete_last_page": "Impossible de supprimer la dernière page. Le document doit contenir au moins une page.",
    "err_invalid_page_index_val": "Index de page invalide : {}",
    "success_page_deleted": "Page {} supprimée.",
    "err_deleting_page": "Erreur lors de la suppression de la page : {}",
    "err_moving_shape": "Erreur lors du déplacement de la forme : {}",
    "err_during_op": "Erreur lors de l'opération : {}",
    "dbg_embedded_font_found": "DEBUG : Répertoire des polices intégrées trouvé : {}",
    "err_embedded_font_not_found": "ERREUR : Répertoire des polices intégrées introuvable : {}",
    "warn_scanning_dir": "Avertissement : Erreur lors de l'analyse du répertoire {} : {}",
    "font_scan_completed": "Analyse des polices terminée. {} familles trouvées.",
    "wait_font_scan": "En attente de la fin de l'analyse des polices…",
    "err_font_scan_timeout": "ERREUR : Délai d'analyse des polices dépassé.",
    "dbg_repaired_while_opening": "DEBUG : Ce fichier PDF a été réparé à l'ouverture.",
    "dbg_save_success": "DEBUG : Enregistrement réussi. Rechargement : {}",
    "btn_open_label": "_Ouvrir",
    "btn_cancel_label": "_Annuler",
    "font_tip_original": "Police (PDF original : {})",
    "dbg_discarding_unsaved": "Abandon des modifications non enregistrées.",
    "import_pdf_title": "Importer un PDF",
    "import_pdf_confirm": "Voulez-vous fusionner '{}' dans le PDF actuel ou l'ouvrir ?",
    "err_merge_title": "Erreur de fusion PDF",
    "open_pdf_title": "Ouvrir un fichier PDF",
    "save_as_title": "Enregistrer le PDF sous...",
    "export_as_title": "Exporter sous...",
    "status_exporting": "Exportation au format {}...",
    "err_unknown_export_format": "Format d'exportation inconnu.",
    "status_exported": "Exporté en {} : {}",
    "err_export_failed_msg": "Échec de l'exportation : {}",
    "err_export_unexpected": "Erreur inattendue pendant l'exportation : {}",
    "status_export_failed": "Exportation échouée.",
    "err_no_doc_msg": "Veuillez d'abord ouvrir ou créer un document.",
    "err_no_doc_title": "Aucun document",
    "err_add_page_title": "Erreur d'ajout de page",
    "err_no_doc_open_msg": "Veuillez d'abord ouvrir un document.",
    "err_cannot_delete_last_page_title": "Impossible de supprimer la page",
    "delete_page_warn_msg": "La page {} sera supprimée. Cette opération ne peut pas être annulée. Continuer ?",
    "delete_page_warn_title": "Supprimer la page",
    "err_delete_page_title": "Erreur de suppression de page",
    "err_move_page_title": "Erreur de déplacement de page",
    "err_fonts_scanning_msg": "Les polices sont en cours d'analyse. Veuillez patienter.",
    "err_fonts_scanning_title": "Analyse des polices",
    "font_user_added": "{} (Ajouté par l'utilisateur)",
    "err_delete_image_failed": "Impossible de supprimer l'image : {}",
    "delete_error_title": "Erreur de suppression",
    "dbg_applying_changes_before_tool": "Application des modifications avant le changement d'outil...",
    "dbg_tool_changed_to": "Outil changé pour : {}",
    "dbg_creating_drag_cmd": "DEBUG : Création de la commande pour l'opération de déplacement.",
    "dbg_saving_pending_format_cmd": "DEBUG : Enregistrement du changement de format en attente.",
    "status_new_doc_created": "Nouveau document vide créé. N'oubliez pas d'enregistrer.",
    "err_adding_image_dialog": "Erreur lors de l'ajout de l'image : {}",
    "err_title": "Erreur",
    "mode_edit": "Édition",
    "mode_view": "Affichage",
    "mode_toggle_tip": "Basculer entre le mode Affichage et Édition",
    "tools": "Outils",
    "highlight": "Surligner",
    "highlight_tip": "Surligner le texte sélectionné",
    "highlight_color_tip": "Couleur de surlignage",
    "remove_highlight": "Supprimer le surlignage",
    "remove_highlight_tip": "Supprimer le surlignage du texte sélectionné",
    "save_error_title": "Erreur d'enregistrement",
    "text_extract_error": "Impossible d'extraire la structure de texte de la page {}.\n{}",
    "highlight_failed": "Échec du surlignage : {}",
    "filter_pdf": "Fichiers PDF (*.pdf)",
    "filter_all": "Tous les fichiers",
    "filter_word": "Document Word (*.docx)",
    "filter_odt": "Texte OpenDocument (*.odt)",
    "filter_pptx": "Présentation PowerPoint (*.pptx)",
    "filter_odp": "Présentation OpenDocument (*.odp)",
    "filter_txt": "Fichier texte (*.txt)",
    "new_doc_dialog_title": "Nouveau document",
    "new_doc_create": "Créer",
    "new_doc_cancel": "Annuler",
    "new_doc_page_setup": "Configuration de page",
    "new_doc_template": "Modèle",
    "new_doc_orientation": "Orientation",
    "new_doc_portrait": "Portrait",
    "new_doc_landscape": "Paysage",
    "new_doc_dimensions": "Dimensions",
    "new_doc_unit": "Unité",
    "new_doc_width": "Largeur",
    "new_doc_height": "Hauteur",
    "new_doc_document": "Document",
    "new_doc_num_pages": "Nombre de pages",
    "new_doc_pages_desc": "Pages vierges initiales",
    "new_doc_unit_mm": "Millimètres (mm)",
    "new_doc_unit_cm": "Centimètres (cm)",
    "new_doc_unit_in": "Pouces (in)",
    "new_doc_unit_pt": "Points (pt)",
    "new_doc_unit_px": "Pixels (px @ 72 dpi)",
    "preset_a4": "A4 (210 × 297 mm)",
    "preset_a3": "A3 (297 × 420 mm)",
    "preset_a5": "A5 (148 × 210 mm)",
    "preset_a6": "A6 (105 × 148 mm)",
    "preset_a2": "A2 (420 × 594 mm)",
    "preset_a1": "A1 (594 × 841 mm)",
    "preset_a0": "A0 (841 × 1189 mm)",
    "preset_b4": "B4 (250 × 353 mm)",
    "preset_b5": "B5 (176 × 250 mm)",
    "preset_letter": "US Letter (8.5 × 11 in)",
    "preset_legal": "US Legal (8.5 × 14 in)",
    "preset_executive": "US Executive (7.25 × 10.5 in)",
    "preset_tabloid": "Tabloid / Ledger (11 × 17 in)",
    "preset_slide_16_9": "Diapositive 16:9 (1920 × 1080 pt)",
    "preset_slide_16_10": "Diapositive 16:10 (1920 × 1200 pt)",
    "preset_slide_4_3": "Diapositive 4:3 (1024 × 768 pt)",
    "preset_square": "Carré (1080 × 1080 pt)",
    "preset_custom": "Personnalisé...",
}

import unittest


class TestFrenchLocales(unittest.TestCase):
    def test_french_dictionary_populated(self):
        self.assertGreater(len(fr), 300)
        for k, v in fr.items():
            self.assertTrue(v, f"Empty translation for {k}")


if __name__ == '__main__':
    unittest.main()
